YunoHost/yunohost-admin

- src/js/app.js
I have redo the commit in a new branch because the previous pull request was a little crazy. I don't use often git (I work with mercurial) so sometimes I make mistakes.
> [fix] Link broken on security alert (#95)

- debian/control
- debian/rules
/!\ Do not merge before squashing commits /!\
> Fix deb nodejs

- src/js/yunohost/controllers/apps.js
see https://github.com/YunoHost/yunohost/pull/173
> [fix] api correctly returns boolean value now

- src/index.html
add noscript tag, to say activate javascript when javascript is deactivate 
No data-y18n because localisation doesn't work without javascript
inspiration come from https://twitter.com/brabram/status/784463217821097984
> Add noscript tag

- src/gulpfile.js
- src/js/yunohost/controllers/home.js
- src/js/yunohost/events.js
- src/js/yunohost/main.js
Feel free to suggest any changes or other possible implementations :smiley:
> [enh] Show version only when connected

- src/js/yunohost/controllers/apps.js
- src/js/yunohost/controllers/backup.js
- src/js/yunohost/controllers/domains.js
- src/js/yunohost/controllers/firewall.js
- src/js/yunohost/controllers/home.js
- src/js/yunohost/controllers/monitor.js
- src/js/yunohost/controllers/postinstall.js
- src/js/yunohost/controllers/services.js
- src/js/yunohost/controllers/tools.js
- src/js/yunohost/controllers/users.js
- src/js/yunohost/helpers.js
- src/js/yunohost/y18n.js
WIP. Please do not merge right now.
> [enh] Variable assignment code cleanup.

- src/locales/en.json
Fixes https://dev.yunohost.org/issues/849
> [fix] Add "OK" in translatable strings (modal dialog for system upgrade)

- src/locales/fr.json
Reverts YunoHost/yunohost-admin#179
> Revert "Update fr.json"

- src/js/yunohost/controllers/apps.js
- src/js/yunohost/filters.js
- src/locales/en.json
- src/views/app/app_actions.ms
Admin UI for the actions. It reuse the mechanisms of the installation form to be generic (this also open the path of doing this for apps remove/upgrade/others).
Nearly absolutely no work as been done on the UI part, it reuses app install form.
Obligatory screenshot:
I think it's more important to make that available to app devs to gather their feedback that to work on other things for now.
> App actions

- src/js/yunohost/controllers/home.js
(Microdecision, waiting for Bram's opinion in case this is needed for some reason)
> Remove forgotten console.log

- src/js/yunohost/controllers/apps.js
- src/locales/en.json
- src/views/app/app_install.ms
- src/views/postinstall/postinstall_3.ms
- src/views/tools/tools_adminpw.ms
- src/views/user/user_create.ms
- src/views/user/user_edit.ms
Related to https://github.com/YunoHost/yunohost/pull/196
> Add comments about good practices for choosing passwords

- src/js/yunohost/controllers/apps.js
- src/views/app/app_install.ms
Integration of https://github.com/YunoHost/yunohost/pull/697 / https://github.com/YunoHost/yunohost/pull/669
Use this app if you want to test https://github.com/Psycojoker/display_text_ynh
> [enh] support display_text

- src/views/app/app_actions.ms
Cleaner correction than: https://github.com/YunoHost/yunohost/pull/708
> [FIX] app actions

- src/views/app/app_info.ms
To be merged with:
https://github.com/YunoHost/yunohost/pull/730
> display the current version of the app

- src/css/style.less
Proposal for a minor aesthetic change
Before : 
After :
> Bolder app names

- README.md
fixes https://github.com/YunoHost/issues/issues/1469
> Add correction : js-cookie

- src/js/yunohost/controllers/domains.js
Needed by https://github.com/YunoHost/yunohost/pull/796
> [mod] rename parameters according to changes in cli/core for ux

- src/js/yunohost/controllers/apps.js
- src/views/app/app_list_install.ms
Reverts YunoHost/yunohost-admin#207
> Revert "[fix] Try something to be independent from github"

- src/views/app/app_config-panel.ms
same as: https://github.com/YunoHost/yunohost-admin/pull/239
> [FIX] app config panel

- src/js/yunohost/controllers/apps.js
https://forum.yunohost.org/t/yunohost-3-8-testing-call-for-feedback/10870/112
> [Fix] install button in case of multi instance capability

- src/locales/en.json
Typo fix in nginx error message
> Typo fix in nginx error message

- src/js/yunohost/controllers/backup.js
- src/views/backup/backup_info.ms
c.f. https://github.com/YunoHost/issues/issues/838
Updated view :
> Small rework of backup view + add backup download button

- src/views/backup/backup_create.ms
Bug reported [here](https://forum.yunohost.org/t/yunohost-4-1-testing-call-for-feedback/13488/5)
This value has been changed during the permission v2 refactor.
Tested on my side and works well
> Fix the creation of a backup

- app/src/i18n/locales/en.json
> Add cap H to YunoHost

- app/src/api/handlers.js
should fix https://github.com/YunoHost/issues/issues/1772
Yolocommited
> replace backslash n with <br>

- app/package.json
- app/src/api/errors.js
- app/src/store/info.js
- app/src/views/PostInstall.vue
- app/src/views/app/AppConfigPanel.vue
- app/src/views/service/ServiceInfo.vue
- app/src/views/update/SystemUpdate.vue
> small fixes 4.2.3

- app/src/views/user/UserEdit.vue
Fix https://github.com/YunoHost/issues/issues/1796
Tested in ynh-dev
> [fix] Empty quota doesn't work

- app/src/views/user/UserEdit.vue
Fix https://github.com/YunoHost/issues/issues/1812
> [fix] User edition: alias and password change

- app/src/views/diagnosis/Diagnosis.vue
Fix https://github.com/YunoHost/issues/issues/1818
Tested on ynh-dev
> [fix] Ignore button is broken

- app/src/views/backup/BackupCreate.vue
- app/src/views/backup/BackupInfo.vue
- app/src/views/tool/ToolMigrations.vue
> [fix] Request with array args

- app/src/views/app/AppInstall.vue
Quick and dirty patch
Fix https://github.com/YunoHost/issues/issues/1832
> fix argument-less manifest

- app/src/views/app/AppInfo.vue
> [fix] Link to app on operation panel

- app/package-lock.json
- app/package.json
Fix #370
Fix #365 
Fix #364 
Fix #361
Fix #360
Fix #359
Fix #353
> run npm audit fix

- app/src/views/user/UserList.vue
Need CSV PR https://github.com/YunoHost/yunohost/pull/1089
Untested
> [enh] Filter by groups

- app/src/views/domain/DomainDns.vue
should fix https://github.com/YunoHost/issues/issues/1879
> simplify 'push dns records' callback

- app/src/App.vue
- app/src/i18n/locales/en.json
- app/src/scss/main.scss
- app/src/views/tool/ToolLog.vue
Because I'm so fucking tired of people copypasting only the last lines and then you have to ask them to go back and click the damn green button
> Make logs unselectable to force people clicking the damn share button >_>

- app/src/helpers/yunohostArguments.js
- app/src/views/app/AppConfigPanel.vue
- app/src/views/app/AppInstall.vue
- app/src/views/domain/DomainConfig.vue
- app/src/views/user/UserCreate.vue
- app/src/views/user/UserEdit.vue
should fix https://github.com/YunoHost/issues/issues/1885
Not fully tested !
> App install visible

- app/src/views/app/AppConfigPanel.vue
> Fix apps config panel apply call

- app/src/helpers/yunohostArguments.js
- app/src/store/data.js
c.f. https://github.com/YunoHost/yunohost/pull/1420
> configpanels: logic regarding dynamic-choices questions such as domain, user, should be handled by the core

- app/src/helpers/yunohostArguments.js
- app/src/store/data.js
- app/src/views/app/AppInfo.vue
- app/src/views/domain/DomainConfig.vue
See https://github.com/YunoHost/yunohost/pull/1406
> Manage default application using DomainConfig

- app/src/views/app/AppInstall.vue
See https://github.com/YunoHost/yunohost/pull/1427
> Clean unused API calls

- app/src/i18n/locales/en.json
- app/src/store/info.js
- app/src/views/Login.vue
Quick update of login form with username input
> login: add card-form with admin username input to login

- app/src/router/routes.js
- app/src/views/Home.vue
- app/src/views/tool/ToolList.vue
> Move service view to 'Tools' section (+ tweak icons)

- app/src/i18n/helpers.js
- app/src/main.js
Looks ok from dev env, dunno if its the best approach but that should do the trick
> fix: wait for locales to be loaded before mounting the app

- app/src/i18n/locales/en.json
- app/src/i18n/locales/fr.json
- app/src/store/data.js
- app/src/views/user/UserCreate.vue
- app/src/views/user/UserEdit.vue
cf https://github.com/YunoHost/yunohost/pull/1516
> Merge firstname and lastname info

- app/src/components/MessageListGroup.vue
- app/src/components/globals/YunoListGroupItem.vue
- app/src/helpers/yunohostArguments.js
- app/src/views/diagnosis/Diagnosis.vue
Switch to uncoloured backgrounds for list-group-item in diagnosis and future items
> New list-group-item styling for diagnosis

- app/src/store/data.js
- app/src/views/domain/DomainInfo.vue
- app/src/views/domain/DomainList.vue
- app/src/views/user/UserCreate.vue
- app/src/views/user/UserEdit.vue
should fix https://github.com/YunoHost/issues/issues/2117
This is a temp fix, will be reworked on the vue3 migration
> fix main_domain api call with ugly cache override from domain list

- app/src/views/Login.vue
Closes https://github.com/YunoHost/issues/issues/2151
> fix: correctly set autocomplet attribute on login form inputs

- app/src/i18n/supportedLocales.js
- app/vue.config.js
Update supported locales and update date-fns locales list.
fix https://github.com/YunoHost/issues/issues/2171#issuecomment-1455138041
> locales: add ckb da he id kab lt mk pt_BR sl

- app/src/helpers/yunohostArguments.js
- `Option.name` -> `Option.id`
- remove mentions of `current_value`
- remove parsing of `min` + `max` of `type = "boolean"`
To merge after https://github.com/YunoHost/yunohost/pull/1651
> ConfigPanel: Reflects changes from pydantic migration

- app/src/i18n/locales/en.json
- app/src/i18n/locales/fr.json
- app/src/views/app/AppInfo.vue
- app/src/views/app/AppInstall.vue
fix https://github.com/YunoHost/issues/issues/2341
> add package license link in AppInfo + AppInstall

- README.md
- the screenshot and the weblate picture does not have a proper alt text, i added it
- i changed the way of declaring titles to use the one used everywhere else by YunoHost
- i also added some break lines
done
> Readme: add pictures alt text and some markdown standardization

- app/index.html
cf https://forum.yunohost.org/t/anonymising-links-in-app-specific-documentation/30258
https://stackoverflow.com/questions/6817595/remove-http-referer
(Yolocommited, untested)
> Disable sending referer when clicking on links to external websites

- app/src/components/globals/ViewSearch.vue
- app/src/i18n/locales/en.json
- app/src/views/app/AppCatalog.vue
- app/src/views/app/AppInstall.vue
- propose to remove criterias when no search results and criterias
- propose to add or vote for the app on the wishlist when no search results and no criterias
- propose to vote for the app with direct link to its catalog page if app is lowquality or lesser in AppInstall
Ready
The current link to the wishlist includes the current webadmin's catalog search value but looks like the app wishlist cannot be queried with a search param.
fix https://github.com/YunoHost/issues/issues/2369
> Enh: Mention the wishlist/vote system in the webadmin

- app/package.json
- app/src/views/app/AppInfo.vue
- app/src/views/group/GroupCreate.vue
- app/yarn.lock
Misc small bookworm fixes. Upgraded without full test `bootstrap-vue-next` to fix the modal error problem
fix https://github.com/YunoHost/issues/issues/2473
fix https://github.com/YunoHost/issues/issues/2472
fix https://github.com/YunoHost/issues/issues/2459
> Bookworm fixes

- app/src/i18n/locales/en.json
- app/src/types/core/api.ts
- app/src/views/tool/ToolFirewall.vue
See https://github.com/YunoHost/yunohost/pull/2011 for details
Current status:
> Adapt webadmin to the new firewall API

- app/src/components/globals/formItems/AdressItem.vue
- app/src/components/globals/formItems/CheckboxItem.vue
- app/src/components/globals/formItems/FileItem.vue
- app/src/components/globals/formItems/InputItem.vue
- app/src/components/globals/formItems/SelectItem.vue
- app/src/components/globals/formItems/TagsItem.vue
- app/src/components/globals/formItems/TagsSelectizeItem.vue
- app/src/components/globals/formItems/TextAreaItem.vue
- app/src/views/user/UserEdit.vue
'disabled' props and some others were not apply to components.
Fix https://github.com/YunoHost/issues/issues/2495
> Fix: missing props on form items

- app/src/components/globals/formItems/InputItem.vue
- app/src/types/form.ts
- app/src/views/LoginView.vue
requested by https://framapiaf.org/@nicolagaffe/114151153818311867
> login: autofocus the username field on page load
