YunoHost/yunohost-admin

debian/control

lintian complains about the use of "allow one to".
modify the description to get rid of it.

[fix] Modify package description (lintian)

---

src/js/yunohost/controllers/apps.js

This is *quite an urgent* bug since it prevent any boolean fields - defined in the app manifest - to be unchecked... Hopefully it only concerns a few applications - such as ownCloud, see the [concerned argument](https://github.com/YunoHost-Apps/owncloud_ynh/blob/master/manifest.json#L56-L62).

[fix] Ensure checkbox is not required for boolean fields

---

README.md
src/package.json

* `bower` and `gulp` are already part of `devDependencies` and we might as well use them instead of requiring to install them globally, this means the module is self contained and we can know for sure which versions of `bower` and `gulp` to use.
* added `postinstall` npm script which is invoked after dependencies have been installed, which we can use to call `bower install` to install the rest
* added `build` and `build-dev` npm scripts to call `gulp` which is already installed

simplify install and build

---

src/locales/en.json
src/views/user/user_info.ms

See https://dev.yunohost.org/issues/640
With the change made by https://github.com/YunoHost/yunohost/pull/186 the presentation of the mailbox quota was a bit misunderstandable.
**Before this PR on yunohost admin:**
Mailbox Quota 	5M / 500M -> ok
Mailbox Quota 	5M / No Quota -> here 5M is the mailbox used space
Mailbox Quota 	? / No Quota -> here 5M is the mailbox used space
**After this PR on yunohost admin:**
Mailbox Quota 	        500M
Mailbox used space 	5M
Mailbox Quota 	        No Quota
Mailbox used space 	5M
Mailbox Quota 	        No Quota
Mailbox used space 	?

[fix] Avoid incomprehensible info about quota (#640)

---

src/views/service/service_log.ms

Hello,
Trivial fix. Right now, because of `<pre>` behavior, logs in the admin interfaces looks like that:
Following this PR, they look like that:

[fix] avoid empty whitespace for the first line of the logs display

---

debian/postinst

Edit by Alex : 
Fixes https://dev.yunohost.org/issues/857 (`/usr/share/yunohost/admin/` is incorrectly owned by www-data)

[fix] Set document root permission during package install.

---

src/css/style.less
src/js/yunohost/controllers/apps.js
src/views/app/app_install.ms

Help text will work the same way `ask` does in manifest.json ; 
```json
{
"name": "domain",
"type": "domain",
"example": "domain.org",
"ask": {
"en": "Choose a domain for AgenDAV",
"fr": "Choisissez un domaine pour AgenDAV"
},
"help": {
"en": "Help domain",
"fr": "Aide domain"
}
},
```
Help text will be display at the bottom right of every field on the app installation form.
Some specific fields already have a help link (domain, user and apps); In the case of both help text from manifest and help link have to be displayed, a line break will be added before help link.
A picture is worth a thousand words ![](https://lut.im/OUPf3Itcdx/UYz7LJHTAsFpQInv.png)

[enh] Display help text from manifest during app installation.

---

src/js/yunohost/controllers/apps.js
src/js/yunohost/main.js
src/locales/en.json
src/views/app/app_appslists_info.ms
src/views/app/app_appslists_list.ms
src/views/app/app_list_install.ms

Addresses https://dev/yunohost.org/issues/875
1- "Manage apps lists" button on /app/install page : 
2- List of apps lists and form to add new list
3- List info and actions (refresh, remove)
- Maybe the "list info" step is unnecessary and the "refresh" and "remove" buttons could live on the big list page.

[enh] Manage appslists. #875

---

src/locales/en.json

Je pense qu'ici on veut rafraîchir le statut des applications "de cette liste" plutôt que "depuis cette liste".

Typo s/from/for/

---

src/js/yunohost/controllers/backup.js

The output of `yunohost backup info` was slightly changed (the 'hooks' key was renamed 'system' for semantic) but this wasn't propagated to the admin interface.
(Probably related issue : https://dev.yunohost.org/issues/949 )
Straightforwardly change the key

[fix] 'hooks' key is now 'system' in backup info

---

src/js/yunohost/helpers.js
src/locales/en.json

At the moment, when the python core crashes because of unhandled exception, or whatever kind of unexpected bug, the web admin shows an obscure "500 Internal Server Error" with basically no explanation about what's going on in the backend (in addition to breaking the CSS of the whole page, c.f. https://dev.yunohost.org/issues/941). Hence it's complicated for people to explain the issue and provide useful information to help debugging (the only way is to try to run the same operation in CLI).
Illustration : 
The moulinette actually didn't handle properly Exceptions from the python code. Now that https://github.com/YunoHost/moulinette/pull/142 handles it, we can display a nice message with proper explanation and details. (The only dirty thing is that I added a bunch of html code in the …

[fix] Correctly handle error 500

---

src/locales/en.json
src/views/domain/domain_dns.ms

Users who go to the 'DNS conf' page sometimes think that this shows some sort of actual configuration. We should tell them explicitly that this is only the recommended configuration which should be configured in the registrar.
Related issue on redmine : https://dev.yunohost.org/issues/559
For the CLI, display a warning (see [related PR](https://github.com/YunoHost/yunohost/pull/346)). For the webadmin, display a warning block.

[fix] Tell user that domain dns-conf shows a recommendation only

---

src/js/yunohost/controllers/tools.js
src/locales/en.json
src/views/update/update.ms

Some times user could be suspicious against one app, and don't want to upgrade it
Add a button to update just an app in the Update view
This PR is related to the yunohost-api PR https://github.com/YunoHost/yunohost/pull/359
You can test with by upgrading an app.
To be able to upgrade an app, you can change the update_time by editing your apps settings /etc/yunohost/apps/APP/settings.yml
Opinion needed

[enh] Upgrade just one app

---

src/js/yunohost/controllers/home.js
src/locales/en.json

IMPORTANT: we'll need to rise the requirement yunohost version for the yunohost-admin .deb package to be sure that this patch will work.
Follow up of https://github.com/YunoHost/yunohost/pull/406 (which needs to be merged first).
Here is the displayed warning:
Don't hesitate to modify the text if you have a better phrasing.

[enh] display warning and instruction to fix meltdown vulnerability

---

src/js/yunohost/events.js
src/js/yunohost/main.js
src/locales/en.json
src/locales/fr.json

To implement https://github.com/YunoHost/yunohost/pull/414  https://dev.yunohost.org/issues/718
Tested, work as expected.

[enh] display stable/testing/unstable in footer

---

src/js/yunohost/controllers/services.js
src/locales/en.json
src/views/service/service_info.ms
src/views/service/service_list.ms

Following the recent changes in the service list, a few users noticed/complained that some services are marked as 'exited' and in red. This is the case for yunohost-firewall and recently postfix (on stretch). But a status 'exited' is apparently okay and just relates to the way the service works (i.e. a daemon staying alive, or just commands being executed at start/stop, like the yunohost-firewall does). Therefore the 'exited' status is okay and in fact the service is active according to systemctl.
c.f. this screenshot : 
Use the `service.active` (=active/inactive) key instead of `service.status` (=running/exited/dead) in views
Not tested because I was too lazy to setup my whole dev env é_è But I should test this at some point in the coming days

Use the active/inactive status instead of running/exited/dead in service views

---

src/locales/en.json
src/views/backup/backup.ms
src/views/backup/backup_create.ms
src/views/backup/backup_info.ms
src/views/backup/backup_list.ms

We still have this warning hanging in the webadmin saying that backup is an experimental feature. But it's not experimental anymore (at least not more experimental than YunoHost :P )
Remove the warnings
Yolo commited, not tested :|

Backup is not experimental anymore

---

src/js/yunohost/controllers/backup.js
src/js/yunohost/helpers.js
src/views/backup/backup_create.ms
src/views/backup/backup_info.ms

This goes with https://github.com/YunoHost/yunohost/pull/490 that removes --hooks but which is still used by the admin. Therefore I replaced `hooks` with `system` where appropriate (or `system_parts` to keep the same semantic).
Doing this, I also noticed a bug due to the fact that the `id` key isn't present in apps info from `backup info` when displaying the corresponding view in the webadmin (fix: use `{{@key}}` instead)

 Rename 'hooks' to system or system_parts in backup stuff

---

src/js/yunohost/helpers.js

We regularly have 'error 0' errors on the webadmin which is a bit cryptic to debug. To help debugging, I propose to include a log of the 'xhr' variable in the console. That might help investigate the cause of the error (at least for us dev :s )

Log 'xhr' variable in console when an unexpected error occur

---

src/views/app/app_list_install.ms

Solve https://github.com/YunoHost/issues/issues/1170
Another label like 'install another' won't be more clear. Just removing the label seems more understandable.
Ljf idea to have a better UX on that point is to always display all apps in the install list but the uninstallable ones should be displayed greyed out. But is this worth it if a brand new app store comes soon ?
I haved just cut the label out.

simply remove the 'installed' label

---

src/js/yunohost/controllers/apps.js
src/js/yunohost/controllers/backup.js
src/js/yunohost/controllers/services.js
src/js/yunohost/controllers/tools.js
src/js/yunohost/main.js
src/views/app/app_appslists_info.ms
src/views/app/app_info.ms
src/views/backup/backup_info.ms
src/views/backup/backup_list.ms
src/views/service/service_info.ms
src/views/service/service_list.ms

The way to manage date was not everywhere the same, this PR try to harmonize the date management.
Current date management doesn't use timezone, so somehour could be wrong.
Use formatTime everywhere to display date in the timezone of the browser.
Consider the API always returns a date containg timezone info. If not the date will be displayed as it with the browser timezone...
Ready
This PR is linked to 
https://github.com/YunoHost/yunohost/pull/552

[enh] Display date in timezone of browser

---

src/js/yunohost/controllers/apps.js
src/locales/en.json

Currently there is no warning shown when installing experimental or low quality apps. We should add some to discourage users installing apps likely to break their system ...
- Ask for confirmation when installing low quality or broken/experimental apps
- A "good quality" app is defined as working + level >= 3
- A "low-quality app is defined as working + level = 1 or 2
- A broken / experimental app is all other apps
- Increase spookiness of message when installing apps from custom URL

[enh] Confirm when installing experimental or low quality apps

---

src/js/yunohost/helpers.js

Currently, if we encounter an error 500, we assume we got a json with a few properties defined and attempt to parse it. However for some reason we might not get such a json and the admin will fail miserably and pacman will keep running forever (and nothing is displayed to the user).
This is related to https://github.com/YunoHost/issues/issues/1196 though I don't expect if to be 100% of the root cause.
I don't know what's a proper solution, I just added a quick and dirty try/catch so that the code doesn't fail miserably and shows the raw `xhr.responseText` as traceback. At least pacman stops moving and something is shown to the user :/

Do not fail miserably if we don't have proper json during error 500

---

src/locales/en.json
src/views/home.ms

Some admins might still be on Jessie and might have not seen the migration about Stretch (e.g. if they don't follow the announcements on the forum). We need to encourage them to switch to Stretch because Jessie is more and more obsolete.
Add a warning message on the home page. (N.B. : this is to be merged and release on jessie)

Add a warning on home page about YunoHost's version being obsolete

---

src/js/yunohost/controllers/home.js

Currently, each time the home page is displayed, several "checks" are re-ran such as the existence of at least one user, fetching the security rss feed, and checking diagnosis for meltdown/spectre, and meanwhile the pacman is loading.
This is no big deal on fast servers, but it takes quite some times on slow hardware like ARM board. You easily end up having to wait ~5 seconds to be able to actually do anything.
Perform checks only the first time home is shown.
Code isn't so pretty but meh can't do much without recoding everything using ES6

Don't run initial checks each time home page is displayed

---

src/js/yunohost/controllers/home.js
src/js/yunohost/controllers/monitor.js
src/js/yunohost/controllers/tools.js
src/js/yunohost/events.js
src/js/yunohost/main.js

See https://github.com/YunoHost/issues/issues/703 and https://github.com/YunoHost/yunohost/pull/291
It's easy to remove `/version` from `yunohost-api`, but the admin relies on it in several place. This problem was blocking for https://github.com/YunoHost/yunohost/pull/291 ...
I tried to have an elegant solution through the moulinette but it was a complete technical mess so I gave up this. Instead, I just rely on the diagnosis route.
The version in the footer is updated after fetching the diagnosis (also used for the meltdown vulnerability check)
I also move the whole "initial checks" stuff to events.js realizing it's probably cleaner and relevant.
Tested, should be working

Remove dependency to GET /version to fetch version

---

src/locales/en.json
src/views/app/app_info.ms
src/views/app/app_install.ms

Since the version number is available, we can display it:
https://github.com/YunoHost/yunohost/blob/bdc78530cfebad160d297e93cfc151f232dfb593/src/yunohost/app.py#L379
Tested, ~noticed a little problem, version is displayed **version** and not **Version** with a big **V**, I don't know why or where to look to fix it.~ works well!

[enh] Display version inside app info

---

debian/postinst
debian/rules
src/index.html

Soooo Goffanon spotted this issue in that we *still* leak the version number in the `<head>` of the webadmin ... this is in fact used to automatically invalidate the cache so we can't simply remove it ...
A trick I found (though not really tested yet) is instead to generate on each local machine a random hash an replace it at install time ...
However, as said on the chat, I am not sure how all of this attempt to leak the version number is worth it ... In practice, since all yunohost admin assets (js, css, ms, ...) are accessible publicly, an attacker could look at the history of changes on those assets to create a script that would do a bunch of request and infer the version number from the hash of the assets ...
Not really tested, to be discussed

Don't use version for cache control

---

src/views/app/app_access.ms

`{{../settings.id}}` doesn't exist, but `{{settings.id}}` does

[fix] href in app/access page are invalid

---

src/js/yunohost/controllers/tools.js
src/views/tools/tools_log.ms
src/views/tools/tools_logs.ms

The current log list is a bit meh, and in particular it's not obvious which operations failed
N.B. : this depends on https://github.com/YunoHost/yunohost/pull/716
- Add an icon showing the success state of the operation (failed, success or ?) ... cf screenshot
- Also, in the page showing a specific log, fix the breadcrumb to use the log name instead of the log path which is really too technical / complicated

[enh] Improve log list

---

src/views/app/app_info.ms

For some app that haven't url, admin panel displays **https://**, this could be confusing.
https://github.com/YunoHost-Apps/synapse_ynh/issues/130
Display url only if settings.domain exists

Do not show URL if app doesn't have one

---

src/views/postinstall/postinstall_3.ms

References:
* https://github.com/YunoHost/yunohost/blob/b3d29238c4bba040b7ad5afdbcc2be7c6a50058d/src/yunohost/tools.py#L129
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-minlength
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-maxlength
This matches the `yunohost` core logic to ensure >=8, <127 on the form level.

Set minlength/maxlength on admin password form

---

src/css/style.less
src/js/yunohost/helpers.js

`ynh_script_progression` is awesome, but the progress bar rendering in the webadmin is a bit funky because of the use of non-monospace font ... Especially the 'dot' which is small compared to the width of the `#`. But that's understood since that's designed for CLI anyway ;)
Change the display code to detect progress bars using a regex, and inject a bootstrap-based progress bar instead : 
Animated version (with https://github.com/YunoHost/yunohost/pull/724 enabled)
Pull the branch and try to install an app like Wordpress

[enh] Convert ascii progress bars to bootstrap progress bar

---

src/locales/en.json
src/views/update/update.ms

The current update view doesn't display the current / new version of apps, so you don't know what you're really upgrading (and personally that makes me kinda suspicious and unlikely to click the upgrade button)
Display 'from X to Y' version in the view (c.f. https://github.com/YunoHost/yunohost/pull/735 )

[enh] Add current / new versions in update view

---

src/css/style.less
src/js/yunohost/controllers/apps.js
src/js/yunohost/events.js
src/js/yunohost/filters.js
src/views/app/app_config-panel.ms
src/views/app/app_info.ms

Matching PR for https://github.com/YunoHost/yunohost/pull/734

Config panel ynh arguments

---

src/css/style.less

I know we have speak about freazing change until 3.7 will be released, but yesterday Jennifer has waited the end of progress bars during 1 day like José during the Brique Camp.
So this small change fix that...

[fix] Progress bars in logs top bar are confusing

---

src/css/style.less
src/index.html

This adds a "Documentation", "Need help?" and "Donate" link in the footer (c.f screenshot below)
I don't know if that's "too much" or not. I guess it's okay, but it adds more visual weight to the interface (so it's slightly less simple and clean) especially when displayed on pages with very few actual content (e.g. user list with only 1 user) ... Any thoughts ?

Advertise documentation, support and donations in footer

---

src/js/yunohost/controllers/apps.js
src/views/app/app_list_install.ms

This PR refers to https://github.com/YunoHost/issues/issues/1117. We can only install package from github.
Add a condition which will test a connection to different API, and that trying to send GET requests to upstream. This PR implements GET command for Gitlab CE and Gitlab.com based-repo.
Work in progress. Don't Merge.

[fix] Try something to be independent from github

---

debian/control

Trying to push buster forward, these changes are probably not necessary. If anyone has an opinion.

[debian/control] upgrade debhelper and nodejs requirements

---

src/js/yunohost/controllers/apps.js
src/views/app/app_actions.ms

The description of the action is not mandatory and may not be an array.
Fix https://github.com/YunoHost/issues/issues/1545

[fix] action description

---

src/js/yunohost/controllers/tools.js

Today I had this not-so-uncommon situation where a user had a failed app install, ask him to share the log, and right after sharing the log, the user realize he could had debug the whole thing himself because the warning was pretty explicit (system ran out of space)
We regularly have this situation where user could debug themselves just looking at the log, but it also legitimately looks like a huge soup of text because of all the DEBUG lines. 
However, just realized tonight that it's in fact pretty cheap (c.f. the diff) to highlight the error and warning lines ...

[enh] Highlight error/warnings/... in tools > logs

---

src/js/yunohost/controllers/services.js

Critical services being : 
- nginx
- ssh
- slapd
- yunohost-api

Hide stop button for critical services ?

---

src/js/yunohost/controllers/tools.js
src/locales/en.json
src/views/tools/tools_log.ms
src/views/tools/tools_logs.ms

Follow-up of https://github.com/YunoHost/yunohost/pull/955
- Did some cleaning about some unused stuff / unecessary complexity related to "we may display other type of logs someday" but it's been a year and we don't
- Minor tweaks about the number of log / lines displayed in log list and log view
- Integrated the list of suboperations in the single log view (here I manually set the second suboperation as failed to show that it displays a red cross icon in that case)

Cleanup + handle suboperations in log views

---

src/js/yunohost/controllers/apps.js

Related to https://github.com/YunoHost/issues/issues/1494
It allows to search in app description when searching in the install app page in the admin
You can test this change by going to Apps>Install a new app>All apps and then try to search, for example "agendav" and then "caldav". The latter should show all results containing "caldav" in their description

Allow search in the app description

---

src/js/yunohost/controllers/users.js

**Problem:** While creating a new user, if there is a space at the starting or end of the username, an error is thrown "Invalid argument 'username': Must be lower-case alphanumeric and underscore characters only"
This is unnecessary error, as when adding new users one after the other, spacebar may be pressed at the end of username as natural a natural typing habit. 
**Solution:** Trim the username before submitting the page.

Trim username while new user creation to eliminate unecessary error

---

src/js/yunohost/controllers/apps.js
src/js/yunohost/filters.js

Uses the default domain given by API to select it in the app install page (may be useful somewhere else too ?).
Needs https://github.com/YunoHost/yunohost/pull/1022 .
Fixes YunoHost/issues#1633.

Select default domain in app install page

---

app/src/store/info.js
app/src/views/_partials/ViewLockOverlay.vue
app/src/views/_partials/WarningDisplay.vue
app/src/views/_partials/index.js

Some important websocket messages are not displayed explicitly like in [upgrade](https://forum.yunohost.org/t/yunohost-4-2-testing/15088/51), permissions change or [post-install](https://github.com/YunoHost/issues/issues/1774#issue-854705226)
Add another dismissible modal to display this message.
Tested on permission change only
Should fix https://github.com/YunoHost/issues/issues/1774
Run the postinstall, try to upgrade, add a permission that a user has already, don't know what other cases there might be.

add warning modal if last ws message is a warning

---

app/src/api/errors.js
app/src/components/globals/CardForm.vue
app/src/i18n/locales/en.json
app/src/views/Login.vue
app/src/views/PostInstall.vue
app/src/views/_partials/DomainForm.vue

Display form validation errors in their respective cards (with auto redirection to the step involved)
Also handle the special case where someone has not enough diskspace (a new card with an error and a button to run the postinstall with `--force-diskspace`)
Should fix https://github.com/YunoHost/issues/issues/1697
Tested on my side but on a already installed system
run the postinstall with some mistakes in every fields (test.nohost.me in domain for example, a weak password, etc)  
If you can, edit https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/tools.py#L304 by replacing the 10 gb limit with 20 or whatever that would trigger the error on your setup.

Fix postinstall validation errors and add --force-diskspace admin equivalent

---

src/locales/en.json
src/views/home.ms

We're in April 2021, Buster was released in June/July 20**19**, Yunohost 4.x in June/July 2020.

stretch: Add obsolete disclaimer on home page

---

app/vue.config.js

- Some language are missing from the language list in webadmin / Outils / Paramètres de l'administration web .
Following a private message in the forum  concerning the translation into Galician (gl) not beeing integrated into the project, I just notice that some of the translations files where not fetch... I don't know if it is the right way to integrate them... I guess we also could add Persian (fa) to the list.

Add missing translations

---

app/src/i18n/locales/en.json
app/src/router/index.js
app/src/router/routes.js

Another proposition for https://github.com/YunoHost/yunohost-admin/pull/391 to fix https://github.com/YunoHost/issues/issues/1844.
It use the same logic and translation keys as the current breadcrumb (in reversed order and limited to the 2 lasts routes) to avoid having duplicated work to do when adding/changing routes.
Some very particular routes would look like this : 
But this could be improved later easily if needed.

[enh] add simplified breadcrumb as document title

---

app/src/components/LazyRenderer.vue
app/src/components/MessageListGroup.vue
app/src/i18n/locales/en.json
app/src/store/info.js
app/src/views/_partials/HistoryConsole.vue
app/src/views/_partials/WaitingDisplay.vue
app/src/views/app/AppCatalog.vue

First commit should fix lags while running quite verbose actions (like upgrade).
The waiting modal will only display 100 messages at a time (users can still go to history to see the full logs), and websocket messages are handle by batches of 50ms instead of constant stream which was triggering way too much repaint cycles.
You can test it by running the api in debug (`yunohost-api --debug`) and adding a new domain from the web admin for example (quite verbose action in debug, about 1000 ws messages)
Also added a new component that act like a viewport observer that will only render its given component if it is in the viewport (lazy rendering). This should fix lags in the app catalog first load and while searching.

Optimization for waiting modal messages and AppCatalog cards rendering

---

app/src/helpers/validators/customValidators.js
app/src/i18n/locales/en.json
app/src/i18n/locales/fr.json
app/src/views/app/AppCatalog.vue

Fix https://github.com/YunoHost/issues/issues/1653 and https://github.com/YunoHost/issues/issues/1901
The following urls should be supported, c.f. independent pending PR in the core : https://github.com/YunoHost/yunohost/blob/171b3b25d9d4cb7aad8b2cbbc5aeb7eee6243a1f/src/yunohost/tests/test_appurl.py#L31

[enh] Support github-independent repo urls and/or pointing to specific branches

---

app/src/components/LazyRenderer.vue

Some users experiencing a weird bug where app cards in the app catalog are not showing up while searching.
It looks like the intersectionObserver on the LazyRenderer component is triggered but it says it's not intersecting (maybe because of concurency timing stuff where the check is made before some card are removed and the hook is executed after those are removed idk).
Add an ugly check on the LazyRenderer component intersection hook to be sure the element is really not in the viewport.

ugly fix LazyRenderer bug

---

app/src/api/api.js
app/src/components/globals/Spinner.vue
app/src/i18n/helpers.js
app/src/i18n/index.js
app/src/i18n/locales/en.json
app/src/main.js
app/src/store/info.js
app/src/views/Login.vue
app/src/views/_partials/ReconnectingDisplay.vue
app/src/views/_partials/ViewLockOverlay.vue
app/src/views/_partials/WaitingDisplay.vue
app/src/views/_partials/index.js
app/src/views/tool/ToolPower.vue
app/src/views/update/SystemUpdate.vue

Issue where users does not reload their admin when upgrading ending up on a possibly broken web admin.
Add a new `ReconnectiongDisplay` component that lock the screen after an upgrade of `yunohost` or `yunohost-admin`, a reboot or a shutdown. It will try to reach the server after a reboot or the restart of `yunohost-api` until it respond then ask for the admin password and finally reload the page (will route to `/yunohost/admin` to be sure we get the last vue `index.html`). Users should ends up connected and on the admin home.
Default values for reconnection:
- attemps: 5 (Infinity for reboot and shutdown)
- delay: 2s between calls
- initialDelay: 0 (2s for upgrade)
This also show what happen when an action ends up with a warning (will display it then tries to reconnect)
If the …

Enh upgrade & power utils with reconnection mecanism

---

app/src/components/globals/CardForm.vue
app/src/components/globals/TabForm.vue
app/src/components/globals/TopBar.vue
app/src/components/globals/formItems/FileItem.vue
app/src/helpers/yunohostArguments.js
app/src/views/app/AppConfigPanel.vue

Several misc fixes
- fix https://github.com/YunoHost/issues/issues/1947
- add ability to have i18n of errors messages in pattern validation:
- in app manifest for example:
```
"pattern": {
"regexp": "^[a-zA-Z0-9-_.]+$",
"error": {
"en": "error",
"fr": "erreur"
},
```
- rework a bit the style and semantic of AppConfigPanel tabs

Enh misc fix

---

app/src/api/errors.js
app/src/store/info.js
app/src/views/tool/ToolMigrations.vue

Fix last lgtm.com alerts (that fix the issue where only the first `\n` of a string is replaced by `<br>`)

fix '\n' replace with replaceAll

---

app/src/components/ConfigPanels.vue
app/src/components/globals/ViewBase.vue
app/src/helpers/yunohostArguments.js
app/src/views/app/AppConfigPanel.vue
app/src/views/domain/DomainConfig.vue

Simplify config panels integration in the web-admin with a component and helpers.
See [AppConfigPanel view](https://github.com/YunoHost/yunohost-admin/blob/14194c90d5ebb28d948008c54970ea4a030c8a24/app/src/views/app/AppConfigPanel.vue) or [DomainConfig](https://github.com/YunoHost/yunohost-admin/blob/14194c90d5ebb28d948008c54970ea4a030c8a24/app/src/views/domain/DomainConfig.vue) for the minimal code to write for a config page.
Notes:
- kept the applyConfig method outside of the ConfigPanels component for possible customization and readability.
- force refetch of the config data after an apply call in case there are some side effects that the webadmin wouldn't update (especially in apps where some packager may modify multiple settings from a custom setting setter)
- enforce that `choices` …

Enh config panels integration

---

app/src/helpers/yunohostArguments.js

Yikes! `arg.choices` is not an `Array` anymore!

[fix] App install is broken when there's choices and the type is string

---

app/src/App.vue
app/src/store/settings.js

On first initialization, `theme`'s localStorage value is unset leading to a white logo with the default light-mode.
Use `theme` settings store value for initial setup and default to light-mode for unset localStorage value.

fix dark mode initialization & default to light theme

---

app/src/components/globals/YunoAlert.vue
app/src/i18n/locales/en.json
app/src/views/app/AppInfo.vue

fix what was intended in https://github.com/YunoHost/yunohost/pull/1631
fix https://github.com/YunoHost/issues/issues/2176
If an error occurs while getting the config panel, instead of blocking the view, it now display the error above the config panel section, and the expected config panel section still display common operations.

Fix config panel apply with empty `args` + fix config panel init error preventing AppInfo from being displayed

---

app/src/views/app/AppInfo.vue

This add a link to the package repo on the app page.
The icon was already there https://github.com/YunoHost/yunohost-admin/blob/86002daa29e88f707865d85243796e84811b131f/app/src/views/app/AppInfo.vue#L357
Yolocommit (I don't have a dev env right now)

Add link to the package repo

---

app/src/i18n/locales/en.json
app/src/views/app/AppInfo.vue

Display a checkbox to purge the datadir if the app has support_purge: true
Should fix https://github.com/YunoHost/issues/issues/1854
Also fix access to `app.from_catalog.git.url` for custom apps

[enh] add --purge option in app uninstall modal

---

.github/workflows/eslint.yml

Node 12 version is deprecated since April 2022.
> Node.js 12 actions are deprecated. For more information see: [github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2

chore: update actions version to use node 16 version

---

app/index.html

on iPhone and iPad, Safari zooms automatically when the user clicks on an input field
but Safari does not automatically zoom out once the field has been filled in, so the user must do it themselves afterwards 
however, this feature makes no sense with interfaces adapted to mobile screens, so it's just annoying for nothing
so I made this PR to disable this feature 😞
the relevant code:
`maximum-scale=1, user-scalable=yes`

Disable safari automatic zoom on input field

---

.github/workflows/eslint.yml

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

chores: update actions/checkout@v3 to v4

---

app/src/i18n/locales/en.json
app/src/i18n/locales/fr.json

linked to https://github.com/YunoHost/apps/pull/2055
as i don't know how to add the "Package license" and it's link, i juste edited the "App license" text
TODO:

rename 'License' to 'App license"

---

app/src/App.vue
app/src/helpers/yunohostArguments.js
app/src/router/index.js
app/src/store/info.js
app/src/views/Login.vue
app/src/views/PostInstall.vue
app/src/views/_partials/ReconnectingDisplay.vue

Misc fixes from current bookworm branch that could be merged before (will rebase bookworm)
- fix context evaluation (visible/enabled props on Options) in simple forms (app install form)
- refactor app init stuff in single hook
- use main domain in the header sso link or fallback to hostname

Misc fixes

---

app/src/helpers/validators/customValidators.js

The code does not allow a "+" on the email local part.
I think this is not the only one that missing:  https://datatracker.ietf.org/doc/html/rfc2822#section-3.2.4

Allow plus on email

---

app/src/i18n/locales/en.json

the sentence 
> Be aware that it may overwrite manually or important default records set by you or your registrar.
is really weird and confusing
i tried to fix it with:
> Be aware that it may overwrite **manual configuration** or important default records set by you or your registrar.

fix a weird sentence

---

app/src/App.vue
app/src/components/globals/formItems/CheckboxItem.vue
app/src/helpers/validators/customValidators.ts
app/src/i18n/locales/en.json
app/src/views/PostInstall.vue
app/src/views/_partials/DomainForm.vue

- add TOS link in footer
- add TOS acknowledgement in dyn domain addition
- add TOS acknowledgement in post install

Enh: add TOS links and acknowledgement

---

app/src/views/domain/DomainDns.vue
app/src/views/domain/DomainInfo.vue

- we display suggested DNS records for special-use domains
- since auth infos for auto DNS push feature are now optional, there's no errors for misconfigured registrar. 
- display error when the feature is activated
- hide suggested DNS records for special-use domains
- do not show that the auto dns are ok when they're not :/
OK
Requires: https://github.com/YunoHost/yunohost/pull/1951

Enh: Make auto dns feature optional

---

app/components.d.ts
app/src/components/globals/ModalForm.vue
app/src/i18n/locales/en.json
app/src/types/core/api.ts
app/src/types/core/data.ts
app/src/views/PostInstall.vue
app/src/views/_partials/DomainForm.vue
app/src/views/app/AppInstall.vue
app/src/views/domain/DomainAdd.vue

- sometimes you just want to add a subdomain, being able to just enter the subpath with your already added domain is less error prone.
- in AppInstall view you are sometimes required to add a specific subdomain for an app, having to return to DomainAdd to setup said new domain then run the diagnosis or force install a Let's Encrypt certificate is tedious.
- add subdomain option to DomainForm with ability to auto install the Let's encrypt certificate if a wildcard is detected in DNS records
- add ability to add a domain/subdomain directly in the AppInstall view in the `domain` field, as a modal, with auto select of the newly added domain.
could'nt test the letsencrypt install properly (can't install certs on my setup idk why)
Requires: https://github.com/YunoHost/yunohost/pull/1936
Fix: …

enh: subdomain addition + domain addition in app install

---

app/src/composables/useInfos.ts
app/src/i18n/locales/en.json

"Automatically" was mispelled "automaticly" and "criterias" was corrected to "criteria", which is the plural of criterion.

Fixed some typos

---

README.md
maintenance/clean_locales.py
maintenance/rename_i18n_keys.py

Added a script so that you can rename a nested i18n key in 'en' or all locales.
This won't change the value, only move the key.
Also added commands to README.md
If you need to rename a key or more (from 'my.current.key' to 'my.new.key' for example).
From a string
```bash
python3 rename_i18n_keys.py --keys my.current.key:my.new.key
```
From a file
```bash
python3 rename_i18n_keys.py --file input.txt
```
input.txt
```
my.current.key:my.new.key
my.other.key:my.new.other.key
```
By default it renames keys only in the `en.json`, pass `--all` to apply changes to all locales file.

Enh: add maintenance script to rename a key in locales

---

app/components.d.ts
app/src/components/ConfigPanels.vue
app/src/components/globals/CardForm.vue
app/src/components/globals/YCard.vue
app/src/components/globals/YListItem.vue
app/src/composables/configPanels.ts
app/src/composables/useAutoModal.ts
app/src/router/routes.ts
app/src/scss/_variables.scss
app/src/types/configPanels.ts
app/src/types/core/api.ts
app/src/types/core/data.ts
app/src/types/core/options.ts
app/src/views/app/AppInfo.vue
app/src/views/app/AppList.vue
app/src/views/app/appData.ts

Reflects change from https://github.com/YunoHost/yunohost/pull/1917
- use config panels instead of previous Operations tab in AppInfo

app/permissions: Move permissions data out of LDAP, introduce a new 'app core' config panel allowing to change the app logo, label, etc.

---

app/src/views/user/UserEdit.vue

Currently editing user, when one enters `0` as mailbox quota posts back to the API
```
Content-Disposition: form-data; name="mailbox_quota"
No quota
```
This however does not pass validation rules imposed in [actionsmap.yml](https://github.com/YunoHost/yunohost/blob/4e9d94c836fa34b37805bf07b61aa8aa0d9d61e3/share/actionsmap.yml#L101C37-L101C53) hence the request fails.
This posts back value of `0` which is the expected result.

Properly remove mailbox quota

---

app/src/views/HomeView.vue
app/src/views/user/UserList.vue

Simply move Groups and permission link from UserList to Home

refactor: move group/perms link to home directly

---

README.md
app/eslint.config.mjs
app/src/composables/useInfos.ts
app/src/composables/useSSE.ts

We lack observing SSE messages when debugging this feature. Add option thru localStorage to display messages in navigator console.
To activate it, type `localStorage.setItem('debug', true)` in the console and reload the page. 
Deactivate it with `localStorage.setItem('debug', false)` or `localStorage.removeItem('debug')`.

feat: add `debug` option to log sse msg
